### ISSUE TITLE
Unlucky text truncation

### ISSUE THREAD

**Issue by jonashaag** [prefix-dev/pixi#100]
<img width="1023" alt="Screenshot 2023-06-14 at 19 20 18" src="https://github.com/prefix-dev/pixi/assets/175722/3a3fb299-4de9-4ef3-ab08-adf2f1c6ea65">

It's truncating to `osx-arm6` although I have enough horizontal space

**Comment by ruben-arts** [comment]
He I think growing it a little would help here, but that would be just for conda-forge. `robostack-humble` for instance would be longer again. 

If we make the loading information auto-scaling it will look better. But it will look horrible when you resize your terminal. e.g.:
![Terminal output after rescaling the terminal](https://github.com/prefix-dev/pixi/assets/12893423/ca85ce6e-1113-442f-a468-2a9cd99dca8e)

What do you think of this solution and what would you prefer?

**Comment by jonashaag** [comment]
Yes, broken TUI scaling is somewhat expected. But I think it should be possible without:

- Clear all progress bars when the command is finished, so no old progress bars are left on the scroll back.
- Handle terminal resizes in the progress bar printing code.

**Comment by baszalmstra** [comment]
We use the [indicatif](https://docs.rs/indicatif/latest/indicatif/) crate for all our progress bar handling. There have been some improvements recently. With the latest release on my machine (Windows) this now happens when the terminal is too small:

https://github.com/prefix-dev/pixi/assets/4995967/5cb3f1aa-571e-4796-955f-4dc7c220f4b9

I think that's already a lot better?
