### ISSUE TITLE
Allow future versions of pixi to read old `pixi.toml` files

### ISSUE THREAD

**Issue by Yura52** [prefix-dev/pixi#1066]
### Problem description

Since backward incompatible changes in file formats are [possible](https://github.com/prefix-dev/pixi?tab=readme-ov-file#status), `pixi.toml` written today can become invalid for future versions of pixi. It would be nice to guarantee that `pixi.toml` files, no matter how old, will remain compatible with future versions of pixi. More details, motivation and ideas can be found in [this discussion](https://github.com/prefix-dev/pixi/discussions/1061).

P.S. My understanding is that `pixi.lock` are guaranteed to be compatible with future versions of pixi by setting the "version" key ([example](https://github.com/prefix-dev/pixi/blob/e04a2ce1a4954a506622618521371b2b7603f249/pixi.lock#L1)). If this is not true, than this issue applies to `pixi.lock` as well.

**Comment by baszalmstra** [comment]
I can safely say that with every change we make strive to be backward compatible. However, we cannot guarantee this while we are very actively developing on pixi. If however, breaking changes are made we will make the path to upgrade very easy.

I can see a future where we will add a version to the `pixi.toml`. But as long as we don't make backward-incompatible changes we most likely won't be adding it because there is no need (the absence of the field would imply version 0).

**Comment by baszalmstra** [comment]
Closing this for now.
