### ISSUE TITLE
moving folders with .pixi dirs produces an ...intimidating error for new pixi users

### ISSUE THREAD

**Issue by ericdill** [prefix-dev/pixi#1081]
### Problem description

As a brand new pixi user (literally less than an hour here), but as a relative conda expert, it took me a bit to grapple with the error message when I reshuffled some folders on disk. One of those folders had a .pixi/ subdir in it. I moved it around, tried to launch my command and was shown the following error:
```
pixi run jupyterhub                                                                                                             
  × the project location seems to be change from `/home/ericdill/dev/anaconda/pnc/jupyterhub-2.2.2/.pixi/envs/default/conda-meta` to `/home/ericdill/dev/anaconda/anaconda-services/customers/PNC/jupyterhub-local/
  │ jupyterhub-2.2.2/.pixi/envs/default/conda-meta`, this is not allowed.
  │ Please remove the `.pixi` folder and run again
```

This error initially made me pretty disappointed because i *thought* that I was going to have to rebuild the whole pixi project config. After DMing Wolf, I am now understanding that this directory is really just where pixi stores its working files (like the conda env), and the fix is really just to do what it says (remove the .pixi folder).

Anyway, mostly just wanted to provide my "hey im a new user around here" feedback on this one.

Some possible ways to educate new users when this happens:
* explain that the .pixi dir is really just a temporary directory and your project files aren't impacted by removing it
* Perhaps a "pixi repair" command or something that just does the stuff that pixi needs in order to start running again.
* Some other even better solution that you brilliant people come up with.

**Comment by ruben-arts** [comment]
He @ericdill, thanks for the feedback! I'm sorry your experience was like this. Sometimes its hard to interpret the experience of a new user when you're as deep in the tool as we are so this is always welcome input.

I'm sure we can figure out a better experience. Some ideas that come to mind are:
- Instead of an error just delete the folder, or give an interactive `Y/n` question if pixi should do it for you. 
- Link to documentation, as the reason we do it also explains some logic that is important in conda. (What an installation actually means appart from linking files)

**Comment by baszalmstra** [comment]
I took the liberty to add an interactive prompt and improve the error message in #1102
