### ISSUE TITLE
Install project in editable mode when using a pyproject.toml manifest automatically

### ISSUE THREAD

**Issue by olivier-lacroix** [prefix-dev/pixi#1083]
### Problem description

With #1044 merged, I propose to automatically add current project as a dependency in editable mode when using a pyproject.toml manifest.

I do not see any reason not to, but maybe I am missing something?

**Comment by tdejager** [comment]
Hi @garymm you are correct in the PR that closes this issue it was decided against an automatic install. Mainly because you can have multiple environments where you *might* not want an editable in all cases.

'pixi unit' does add it automatically to the .toml. If you find this behavior undesirable, feel free to make an issue where we can weigh the pro's and cons :)
