### ISSUE TITLE
Python 2.0 selected when installing with zlib

### ISSUE THREAD

**Issue by benmoss** [prefix-dev/pixi#1292]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

On an osx-arm64 machine with pixi 0.20.1

```shell
pixi init --platform linux-64 --platform osx-arm64
pixi add python zlib
```

### Issue description

It picks Python 2.0 for linux-64 and Python 3.12.3 for osx-arm64

### Expected behavior

I think it should pick 3.12.3 for both

**Comment by baszalmstra** [comment]
Im not sure what to do here. Packages can have different versions on different platforms. This is definitely an extreme example but it is the only correct one. (Btw I retried this specific example and it resolves both pythons to 3.x now).

Im going to close this issue for now because I don't think its actionable.
