### ISSUE TITLE
Add docs to pixi in a devcontainer

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1386]
### Problem description

https://github.com/prefix-dev/pixi/issues/997#issuecomment-2018525722
I'll write some stuff in the coming days

**Comment by lgonzalezsa** [comment]
How to use pixi with devcontainer?

I'm not sure if my use case falls under "not best practice," but I am trying to leverage the work I did already on my devcontainer and build and run an image to execute the code in the same way I am able to do it in the vscode. In order to do that, I installed and tested the devcontainer npm package.

Main reason to use this workflow is to avoid additional changes when I switch dev testing to production.
The `pyproject.toml` file points to local packages (file:// based) that are using `/workspaces/my_project`
I was reading https://github.com/prefix-dev/pixi-docker not sure why my devcontainer does not have any PIXI env variables set as difference when I launch it with vscode. The `my_repo_test` has the `pyproject.toml` file. The bottom line is that I cannot use pixi, here example of the failure:

```bash
vscode@53f28a8e52ab:/workspaces/my_repo_test$ pixi shell-hook
pixi shell-hook
  x could not find pixi.toml or pyproject.toml which is configured to use pixi
  ```
  When I was creating the reproducible example, I face this issue that I recall previously happen as well:
  ```bash
gonluisr@gonluisr-workstation:~/github/pixi_devcontainer$ pixi add papermill
? The environment directory seems have to moved! Environments are non-relocatable, moving them can cause issues.

        /workspaces/pixi_devcontainer/.pixi/envs/default -> /home/gonluisr/github/pixi_devcontainer/.pixi/envs/default

This can be fixed by reinstall the environment from the lock-file in the new location.

Do you want to automatically recreate the environment? (y/n) › yes
```
