### ISSUE TITLE
Tasks not found when switching from `osx-arm64` to `osx-64`

### ISSUE THREAD

**Issue by ekiefl** [prefix-dev/pixi#1404]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
▶▶ pixi init pixi_py --pyproject
✔ Initialized project in /Users/evan/Software/test/pixi_py
▶▶ cd pixi_py/
▶▶ pixi install
✔ Project in /Users/evan/Software/test/pixi_py is ready to use!
▶▶ pixi task add hello "echo hi"
✔ Added task `hello`: echo hi
▶▶ pixi r hello
✨ Pixi task (hello in default): echo hi
hi
```

Now go into `pyproject.toml` and replace `osx-arm64` with `osx-64`.

```shell
▶▶ pixi r hello
 WARN pixi::project::environment: osx-arm64 (Apple Silicon) is not supported by the pixi.toml, falling back to osx-64 (emulated with Rosetta)
hello: command not found
```

### Issue description

![image](https://github.com/prefix-dev/pixi/assets/8688665/06cc082a-2aea-4178-944f-fa6fb3c5d2ea)

On macOS, I have dependencies that don't have support for osx-arm64, which is what pixi determines my platform to be. So I have to manually fallback to osx-64. This poses no problems for installing pixi environments, however tasks are not recognized or run.

### Expected behavior

After switching "osx-arm64" to "osx-64" in the pyproject, i.e.

```toml
[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-64"]
```

I expect the task to be recognized and run:

```shell
▶▶ pixi r hello
✨ Pixi task (hello in default): echo hi
hi

```

**Comment by jjjermiah** [comment]
if i understand correctly, you are switching the value of the `[platforms]` field.

Instead, you should have all platforms listed that you expect the project to work on. 

There was a [short discussion on discord](https://discord.com/channels/1082332781146800168/1242598121901396010) that also explains this a bit. 

So, after you initialize your project successfully and the task you add works, try running:

```
pixi project platform add osx-64
```

instead of replacing the platform in the project.

your platform field should be

```toml
[tool.pixi.project]
channels = ["conda-forge"]
platforms = [ "osx-arm64", "osx-64"]

```

Then pixi should solve the environment for all platforms (even the platform thats not your computer)
- you might need to run `pixi install` for it to do the solving
- this should update the `pixi.lock` file and the environments will be solved for all platforms 
- when the project is then transferred from your M3 Macbook (`osx-arm64`) to a Intel Macbook (`osx-64`), then pixi will recognize that the project is configured for that OS as well

**Comment by ruben-arts** [comment]
@jjjermiah you are correct, however this will not work because of the case @ekiefl describes where he can not install for osx-arm64 because the packages are not available for it. 

We've got some code to get the "best" platform which is why you can install `osx-64` on `osx-arm64` but we indeed missed fixing that for all code, apart from installation. 

We should use the following function in more places!

https://github.com/prefix-dev/pixi/blob/2337654cafe09fb7331e9608e7f208cdcabe9010/src/project/environment.rs#L105-L144

**Comment by ekiefl** [comment]
Hey, just popping in to say thank you for your responsiveness in fixing this issue. I updated our pixi version and no more troubles with osx-arm64 architectures :)

**Comment by wolfv** [comment]
Awesome :)
