### ISSUE TITLE
Ensure that `pixi run` commands work across different platforms.

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#165]
At the moment, executing `pixi run` means that your system shell executes the specified command: https://github.com/prefix-dev/pixi/blob/010bd0675463ffb5a8aa3d557dfd2527ddc24874/src/cli/run.rs#L63

That is similar to how `npm` or `just` works, and it suffers from the same problems.
Users have to either:
- use a common subset of `cmd` and `bash`, or
- workaround it by specifying platform specific commands: https://github.com/casey/just#enabling-and-disabling-recipes

I suggest getting inspired by Deno instead. Deno uses its own cross-platform shell, which is a subset of sh/bash: https://deno.land/manual@v1.34.3/tools/task_runner

The task runner is written in Rust and published on crates.io: https://github.com/jinjor/deno-task-runner 
pixi could therefore directly depend on it. 
It's also only about 6000 lines of code. If you don't like their direction, you could probably fork it and maintain it within this org.
To be extra sure, you could also ask Deno developers if they feel that the deno task runner is a good crate for other projects to depend on.

Alternatives:

- use [nushell](https://github.com/nushell/nushell), you will probably want to wait until 1.0 and even then it will not be a lightweight dependency
- stick with the status quo, after all it seems to work okayish for `npm` and `just` too

**Comment by baszalmstra** [comment]
This is a fantastic idea! 💯 

The current implementation is also cross-platform but it is very limited. We don't allow shell commands to be run. The first argument has to be an existing executable file and all other arguments are quoted. This is very limited in what it can do and we were already planning on enabling some form or running shell commands so your idea sounds great!

We still need the platform-specific shell though because we need to run conda activation scripts which are platform specific. However, we are already working on caching the [result of the activation scripts](https://github.com/mamba-org/rattler/pull/239) so we can run that independently of the running commands with pixi.

It would also be very interesting to use something like this in the conda ecosystem in general though. It's a real pain in the ass to write different build scripts for windows and UNIX.

We'll investigate this further!

**Comment by Hofer-Julian** [comment]
> The current implementation is also cross-platform but it is very limited. We don't allow shell commands to be run. The first argument has to be an existing executable file and all other arguments are quoted. This is very limited in what it can do and we were already planning on enabling some form or running shell commands so your idea sounds great!

Thanks for the clarification @baszalmstra! Seems like I should have looked more closely at the code :)
I am also happy to hear that you are open to the idea, very excited about a future where pixi manages my projects!
