### ISSUE TITLE
Make `pixi shell` inject tasks into shell namespace

### ISSUE THREAD

**Issue by Jollywatt** [prefix-dev/pixi#1772]
### Problem description

This has probably already been considered, but if not, I'd like to be able to run tasks without the `pixi run` prefix in the pixi shell, so that
```
> pixi run test run
[output]
```
would become
```
> pixi shell
> test run
[output]
```
since I'm that lazy.

I imagine this could be done by adding a command in `.pixi/envs/<env>/bin` for each task which simply calls `pixi run <task> <args…>` .

However, this might be problematic if a task with a name such as `test` ends up shadowing built-ins, so feel free to close this as a bad idea!

**Comment by ruben-arts** [comment]
Hi @Jollywatt, this idea has indeed floated around before. But is was indeed turned away because of the overlapping binaries. 

To give this a try you could add a `[activation]``scripts = ["aliases.sh"]` which includes the aliases for you. This is just bash so you could even create a function that automatically creates them from the `pixi task list` command. 

Let me know if this works for you. I'm going to close the issue for now as we're not planning to build this into `pixi shell` right now.
