### ISSUE TITLE
Missing `license` field in `conda-meta/*.json`

### ISSUE THREAD

**Issue by jonashaag** [prefix-dev/pixi#186]
We have an internal tool that reads the `conda-meta` JSONs and generates a license report. It seems like Pixi environments currently don't populate this field.

**Comment by baszalmstra** [comment]
Mmm that's interesting. Rattler does [parse this field](https://docs.rs/rattler_conda_types/0.6.0/rattler_conda_types/struct.PackageRecord.html#structfield.license) the license from the repodata. We also store this information in the lock-file since last release. Apparently, it doesn't get properly propagated to the environment though. 

I'll have to investigate this a little bit further. Does your lock file contain the license information though? Does it contain the information if you recreate it?

**Comment by wolfv** [comment]
I'll have a look :)

**Comment by jonashaag** [comment]
I have licenses in the lock file.
