### ISSUE TITLE
Supporting `uv` configuration

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#1983]
### Problem description

Currently, users are unable to use `uv`’s configuration options. At present, Pixi can only provide a limited number of configuration options via `[pypi-options]`.

Is it possible to let Pixi load `uv`’s configuration options? If compatibility issues arise, there is no need to fix them urgently. Once certain options are deemed stable by Pixi, they can be added under `[pypi-options]`.

There are some options that we urgently need to configure, such as [prerelease](https://docs.astral.sh/uv/reference/settings/#prerelease) and [index-strategy](https://docs.astral.sh/uv/reference/settings/#index-strategy).

**Comment by baszalmstra** [comment]
I think it would be possible for us to port most of these over. But Ill let @tdejager chime in here. :)

**Comment by tdejager** [comment]
Yes we can port most of these over, I've already started on `index-strategy` actually. 

To explain a bit better why this is taking some time:
Ideally you would just rust import the uv options and use these directly, without requiring a translation on our side. However, as I see it, and feel free to convince me otherwise we currently cannot. Because of the following reasons:

1. We sometimes do not want to expose the option (pretty rare), but we opted to only do build isolation per package for example.
2. We need to make decisions to make them work nicely with environments.
3. We might have different reasons for breaking compatibility, by relying on these options directly we are essentialy tied in that respect to uv's release cycle. We might want to deprecate an option more slowely for example.
4. Finally and *most important* a lot of these options are part of the `pixi_manifest` crate, as uv does not publish on crates.io I do not want a git dependency on theres, as there is a big chance we want to publish this crate in the future.

This makes it so it takes a little more time to add these options, sorry about that, but anyone reading it feel free to request any that you are missing.

Hope this gives a bit of insight. Thanks for the issue!

**Comment by zen-xu** [comment]
Thank @tdejager for your reply, I agree with your points, but I believe that any incompatibility resulting from users configuring `uv` options is the user's own responsibility (give a warning?), and the Pixi team does not need to handle these compatibility issues

**Comment by tdejager** [comment]
Thanks @zen-xu this is the PR I mentioned: https://github.com/prefix-dev/pixi/pull/1986

**Comment by zen-xu** [comment]
If I only use `pixi` to manage Conda packages and `uv` to manage PyPI packages, will I encounter any issues?

**Comment by tdejager** [comment]
This works as long as you do not mix conda and pypi dependencies *too much*, as that is where we do some smart mapping translations. E.g you probably get issues when you mix dependencies that depend on `torch` from conda with a PyPI installed torch.

In the example toml above you can make a task that uses `uv pip install -e .` for example to install your project as an editable.

**Comment by zen-xu** [comment]
I think I can close this issue now
