### ISSUE TITLE
Pixi wrongly thinks lockfile is outdated due to symlink

### ISSUE THREAD

**Issue by kcajf** [prefix-dev/pixi#2036]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Install a pypi editable package through a symlink:

pixi.toml:
```
mypackage = { path = "./other-repo-symlink/src/python/mypackage ", editable = true }
```

### Issue description

When solving my environment, pixi always thinks that the lockfile is out of date:
 
```shell
 INFO pixi::lock_file::outdated: the dependencies of environment 'default' for platform linux-64 are out of date because the editable package path 'mypackage', lock does not equal spec path '/data/home/kcajf/code/myrepo/./other-repo-symlink/src/python/mypackage' == '/data/home/kcajf/code/other-repo/src/python/mypackage'
```

On my system, `/data/home/kcajf/code/myrepo/./other-repo-symlink` is a symlink to `/data/home/kcajf/code/other-repo`. These two paths are the same, but pixi doesn't think they are. 

### Expected behavior

Pixi should resolve the real path of these two (or keep them both unresolved), and identify that they are the same.

**Comment by kcajf** [comment]
If, in my `pixi.toml` I hardcode the absolute path, `pixi install` no longer re-solves the lock file. (I can't hardcode the path though, because it needs to be a symlink for portability between internal users / systems).

**Comment by nichmor** [comment]
how do you create the symlink? is it a soft or hard one?

**Comment by kcajf** [comment]
It's a soft/symbolic link.

**Comment by evetion** [comment]
We get the same error on our repo (https://github.com/Deltares/Ribasim-NL/pull/144), where we have a relative path to another checked out repository:

`INFO pixi::lock_file::outdated: the dependencies of environment 'dev' for platform linux-64 are out of date because the editable package path 'ribasim', lock does not equal spec path '/home/runner/work/Ribasim-NL/Ribasim-NL/Ribasim-NL/../Ribasim/python/ribasim' == '/home/runner/work/Ribasim-NL/Ribasim-NL/Ribasim/python/ribasim'`
