### ISSUE TITLE
Change task discovery behaviour with activated pixi environment

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#2473]
### Problem description

When running `pixi shell` or `pixi run` with a manifest in location A, the task discovery currently prefers tasks coming from the manifest in A, rather than the current working directory.

This can lead to surprising behavior, which is why we print
```
 WARN Using manifest A/pixi.toml from `PIXI_PROJECT_MANIFEST` rather than local pixi.toml
```

Let's change the priority from:
- PIXI_PROJECT_MANIFEST
- current working directory
- parent directories

to:
- current working directory
- parent directories
- PIXI_PROJECT_MANIFEST

**Comment by dhirschfeld** [comment]
When I activate a `pixi shell` it's because I want to use the Python environment in that shell and not the one in the local directory - I see it as an explicit command to use to override the local manifest discovery. If I want to use the manifest in the local directory I just `exit` the shell from the other manifest and `pixi` will discover/use the local manifest.

Being able to override the local manifest with one explicitly chosen  is IMO an extremely important capability to enable the typical data-science use-cases. It was having this capability that allowed me to finally switch from `micromamba` to `pixi` as my primary packaging tool.

I mainly care that `(i)python` or `jupyter lab` will open the program from my activated environment and not from the local project `default` environment. I'm not so fussed about task discovery as I don't use them in my analytics environment. If I wanted to e.g. run the local `lint` task when I'm in my activated environment I would just exit the activated shell or would use `pixi run --manifest-path ./pixi.toml lint`

**Comment by Hofer-Julian** [comment]
> I mainly care that (i)python or jupyter lab will open the program from my activated environment and not from the local project default environment.

Is there anything stopping you from moving to the new `pixi global` for this use case?

**Comment by dhirschfeld** [comment]
I don't think `global` environments are a good fit for analytics environments - I see global envs as useful for installing CLI tools rather than Python environments.

I have two primary analytics environments one for Python 3.12. and one for Python 3.10. They have ~the same packages installed. which include a number binaries e.g. `ipython`, `jupyter` plus some CLI tools. It would be possible to go about providing custom `*-310`/`*-312` aliases to each but that's not nice. 

For analytics I want to be able to "activate" an environment (get a shell pointing to the environment) and have that be used for everything, irrespective of what folder I happen to be in. My "activating the environment" (entering a shell for that environment) was an explicit step I took to opt-in to that behaviour.

That's the behaviour we have now and what I'd like to keep, absent an equally simple way to get a shell for an environment that won't be affected by your `cwd`.

**Comment by dhirschfeld** [comment]
I'd turn the question around - what problem are we actually trying to solve here?

If a user wants to do project work in a project directory, it doesn't make sense for them to do that from a shell activated for a different project. I'd say that's a user error and the solution to that is simply to say don't do that.

They get a clear warning that the project isn't activated (because they're in a shell for a _different_ project) and the solution to that user-error is to just type `exit` to get out of the activated shell.

**Comment by Hofer-Julian** [comment]
It's unfortunately not that simple. In practice it's really easy to have PIXI_PROJECT_MANIFEST without being aware of it. We get reports of that all the time, which is why we added the warning to begin with. One common one is open a new vscode window for another project, but it still has PIXI_PROJECT_MANIFEST of the old one

**Comment by dhirschfeld** [comment]
It's unfortunate that it's easy to do by mistake, something which is exacerbated by the fact that VSCode will auto-activate an environment for you so you'd have to know to explicitly exit the shell to start a new VScode session.

Nevertheless, it is still a user error. It doesn't make sense to try and do project work in a shell activated for a different environment.

The warning is very good - it tells users that they have made a mistake so they can then rectify that, but it's still a pain and would be ideally avoided.

I see this particular cure as worse than the disease though. IMO `pixi` shell is a critically important escape-hatch to enable data-science workflows. `pixi` is designed around project-based workflows, and that's great - I use them too, but the more traditional activated environment workflows are also an important part of my daily development.

The proposal here amounts to crippling pixi shell to pretend your not actually in a shell for a different environment because it's inconvenient for people who want to use the project-based workflow. I'm all for making things easy so they Just Work for users, but I think `pixi` needs a way to enable data-science workflows as well as project-based workflows. We have that currently with `pixi shell` and I don't think that workflow should be broken without a viable replacement.

Getting an error message and having to exit your shell or restart your VSCode is inconvenient, but it doesn't prevent you doing anything. Crippling `pixi shell` to be subordinate to the local manifest will prevent typical data-science workflows:
***xref:*** https://x.com/jeremyphoward/status/1822022142592213280

**Comment by dhirschfeld** [comment]
I'm piping up here as I think ~all the core developers use the project-based workflows, and it is great, and I think data-scientists would be well served by adopting it more, but I think `pixi` should still have a way to support typical data-science workflows and I see this proposal as contrary to that.

**Comment by dhirschfeld** [comment]
If having a shell tied to a specified environment really does make project based workflows too inconvenient, maybe there could be two different types of `pixi shell` - one that prefers the local manifest first and another that will always ignore the local manifest in preference to the specified manifest for the shell.

**Comment by ruben-arts** [comment]
Hey @dhirschfeld, 

We want to avoid disrupting the data-science workflow. I think there's a slight misunderstanding.

We're planning the change the manifest discovery logic **not** the activated shell experience. Meaning you aren't forced to use the shell activated manifest when you are anywhere on your machine. I like to think in examples so let me try to explain the proposed situation with a workflow example.

### Example projects folder: 
```
Example projects folder: 
> tree project*
project_a
├── pixi.lock
└── pixi.toml
project_b
├── pixi.lock
└── pixi.toml
```

The activated environment resulting behavior:
```bash
~/ > cd project_a
# Activating project_a's shell
~/project_a > pixi shell
~/project_a (project_a) > python -c 'print("hello from project_a")'

# While moving around the environment stays active like a normal conda environment would.
~/project_a (project_a) > cd ..
~/ (project_a) > python -c 'print("hello from project_a")'
# Pixi commands will act on the activated environment
~/ (project_a) > pixi add matplotlib
~/ (project_a) > pixi list

# It doesn't mater what the contents of the folder is, the environment stays active.
~/ (project_a) > cd project_b
~/project_b (project_a) > python -c 'print("hello from project_a")'
```
In the proposal of this issue, the previous commands will 100% stay the same, and I believe that this is also the most important part for the data-science workflow.

Where the proposal is going to deviate from the current implementation is when you start running `pixi` commands in an activated `pixi shell`. 

**The current behavior:**
```bash
# Running a `pixi` command in other pixi project folders will always act on the activated project, and throw a heavy warning.
~/project_b (project_a) > pixi install
 WARN Using manifest ~/project_a/pixi.toml rather than local ~/project_b/pixi.toml
✔ The default environment has been installed.
 WARN Using manifest ~/project_a/pixi.toml rather than local ~/project_b/pixi.toml
```

**The proposed behavior:**
```bash
# Running a `pixi` command in a pixi project while in another pixi project will run that pixi project instead of the activated one.
# I believe that this should still throw a warning but in the opposite way
~/project_b (project_a) > pixi install
WARN Using manifest ~/project_b/pixi.toml rather than the activated ~/project_b/pixi.toml
✔ The default environment has been installed.
WARN Used manifest ~/project_b/pixi.toml rather than the activated ~/project_b/pixi.toml

# The tasks will use the local cwd project first
~/project_b (project_a) > pixi run python -c 'print("hello from project_b")'
WARN Using manifest ~/project_b/pixi.toml rather than the activated ~/project_b/pixi.toml
hello from project_b
WARN Using manifest ~/project_b/pixi.toml rather than the activated ~/project_b/pixi.toml

# To run pixi specific tasks on the original manifest you should use the `--manifest-path`.
# Which is so explicit it doesn't need a warning anymore. 
~/project_b (project_a) > pixi run --manifest-path $PIXI_PROJECT_MANIFEST "echo echo from \$PIXI_PROJECT_ROOT"
echo from ~/project_a
```

This proposal came out of new users being confused about pixi not acting on the folders they are in. 
There might be ways to simplify how a user can provide which project to use. But please help us understand what that could be if necessary.  

Ps.
I do want to say that the fact that we have this implicit behavior and need warnings to explain to the users what is going on is already a clue that we're touching workflows that will be confusing to at least some users, so I would be still open to a "perfect" solution which is comfortable and intuitive. But I'm having a hard time figuring that out.

**Comment by dhirschfeld** [comment]
Thanks for the clarification! That's definitely the case I'm less worried about:

> *I'm not so fussed about task discovery as I don't use them in my analytics environment.*

It still seems a little unclean to have task discovery work differently, but if it avoids a common pitfall for users, it's probably a net win.

`--manifest-path $PIXI_PROJECT_MANIFEST` is a bit of a mouthful to opt-out of this behaviour (if you did want to). Maybe there could be a flag `--non-local` which would be a alias of `--manifest-path $PIXI_PROJECT_MANIFEST` if you were in an activated shell and a no-op otherwise.
