### ISSUE TITLE
What are the differences between Pixi and Rye?

### ISSUE THREAD

**Issue by linhduongtuan** [prefix-dev/pixi#260]
As far as I know, Pixi and Rye are quite similar?

**Comment by ruben-arts** [comment]
He @linhduongtuan, 

Pixi is build on top of the conda ecosystem, with plans to soon also support pypi. Which means you go a level deeper in to the isolation of the system then you can with only the python world. Because pixi/conda is a binary package manager we use packages build specifically for your platform and architecture. 

This gives the possibility to not just install python packages or python itself as what Rye does but you can also install your non python tools like: Protobuf, CMake, Cudatoolkit, Postgress etc. 

Personally coming from the robotics world we used conda packages for every single dependency of the applications, for all languages we used: Rust, C++ and Python. 

I hope this clarifies it some more.

**Comment by wolfv** [comment]
There are some other things to note:

- Currently rye is a wrapper around piptools. In pixi we implement _everything_ from the ground up in Rust, including download packages, extracting packages, solving for the right versions, ...
- We use conda-forge to get you the Python version you want, while rye uses a build from indygreg (Github Release). We like to depend on a large community of dedicated package people :)
- We are working towards also being able to solve & install PyPI packages using the same solver we use for conda packages. Once we have that, we will be able to properly integrate with the PyPI index as well. This could potentially be shared with rye, for example.

**Comment by linhduongtuan** [comment]
Thank @ruben-arts and @wolfv for your time and explanations

**Comment by ruben-arts** [comment]
Glad to help! Hope you give it a try :smile: Closing this issue!
