### ISSUE TITLE
Add option to create global envs instead of limiting to a project

### ISSUE THREAD

**Issue by ion-elgreco** [prefix-dev/pixi#2611]
### Problem description

I wanted to use pixi with pixi-pack to move full envs to an airgapped system and then do a global env import. However pixi doesn't have this notion, it's all local per project. This won't work well for airgapped systems, as you don't want to do this on project level but global

**Comment by ruben-arts** [comment]
Hey could you explain what you mean with "This won't work well with airgapped systems"?

Here is some more info on features that pixi has that sound related:
- `pixi global` to install tools. Think `pipx` `condax`. 
- [detached environments](https://pixi.sh/latest/reference/pixi_configuration/#detached-environments) could help if you want to have the environment be placed away from the project. 
- Use `eval "$(pixi shell-hook --manifest-path path/to/pixi.toml)"` instead of [`conda activate`](https://pixi.sh/latest/features/environment/#traditional-conda-activate-like-activation).

**Comment by ion-elgreco** [comment]
What I would like pixi to be able to do is this:

1. Create a conda env in non-airgapped environment with pixi
2. Export conda env using pixi-pack as tarball
3. Unpack conda env using pixi-pack to a specified path in the airgapped system
4. Tell pixi this is a global env
5. Tell users to then do `pixi activate v1.2.3`

I essentially want to ship full envs and allow these to be set as global envs.

**Comment by ruben-arts** [comment]
Currently `pixi-pack` gets you very close. the `source activate.sh` would be similar to the `pixi activate` you are proposing. 

@pavelzw do you have some experience with this workflow?

**Comment by ion-elgreco** [comment]
> Currently `pixi-pack` gets you very close. the `source activate.sh` would be similar to the `pixi activate` you are proposing.
> 
> [@pavelzw](https://github.com/pavelzw) do you have some experience with this workflow?

I tried that but didn't really work. A system where I can script global registration, then can then be access with pixi activate "v1.2.3" would be lot's easier

**Comment by ruben-arts** [comment]
Right, for that i would point you to https://github.com/prefix-dev/pixi/issues/1610. This issue goes into more depth, feel free to leave your thoughts if there is something missing. 

Maybe dave's [workaround](https://github.com/prefix-dev/pixi/issues/1610#issuecomment-2451010245) could still work
