### ISSUE TITLE
Fully document pixi.toml format

### ISSUE THREAD

**Issue by kszlim** [prefix-dev/pixi#308]
### Problem description

Hi, I think to increase the ease of adopting pixi, please document fully all the different options in the pixi.toml format and explain each section.

Most of the basics are available, but when I look at examples, there are some uses like (build-dependencies) and host/target that aren't fully documented.

Also some references to other package managers and their features and how they can be replicated within pixi would be helpful (for example dependency groups or optional dependencies).

**Comment by baszalmstra** [comment]
Yes you are completely right. A detailed document about the details of the `pixi.toml` is already underway. Should probably be online this week. We are also planning on writing some comparisons with other package managers but I cant give you a date yet.

**Comment by baszalmstra** [comment]
And here it is: https://prefix.dev/docs/pixi/configuration

**Comment by baszalmstra** [comment]
Yeah we should definitely pay attention to update the docs as we add/change features. We will be merging the docs in this repository soon so we can make sure they are updated with a PR.

`pixi build` is indeed still in development (see this PR: https://github.com/prefix-dev/pixi/pull/85). Do you think it would be better if we'd remove that reference from the documentation until that feature lands? Im a bit on the fence about it because some of the configuration in the `pixi.toml` is mostly there to support `pixi build`.

**Comment by ruben-arts** [comment]
I updated it in the new documentation!
