### ISSUE TITLE
pixi autocompletions: compdef undefined on `zsh`

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#338]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

/

### Issue description

I sat next to someone trying out pixi and after running the install, starting zsh said `compdef undefined`. 

I think this might be an issue in our autocompletion code - removing autocompletions solved it.

### Expected behavior

/

**Comment by ruben-arts** [comment]
Not sure if we should fix this our that the user should update its installation: 
 This would fix it for them.  https://unix.stackexchange.com/a/477909

We could also change the behavior for `zsh` so that it puts the completions in a file and add that file to the `$fpath` But that is a little more steps to update that file when the pixi version changes. 
https://github.com/clap-rs/clap/issues/2479#issuecomment-845312113

**Comment by completementgaga** [comment]
I experienced the same issue on a recent macOS with zsh, it seems plausible that it would suffice to add the two lines
```
autoload -Uz compinit
compinit
```
just before
```
compdef _pixi pixi
```
in the output of 
```
eval "$(pixi completion --shell zsh)"
 ```
I added these two lines in ~/.zshrc just before  ```eval "$(pixi completion --shell zsh)"``` and it solved my issue.
