### ISSUE TITLE
Dynamically Configurable Cache Directory

### ISSUE THREAD

**Issue by trahloff** [prefix-dev/pixi#351]
### Problem description

To speed up Pixi dependency installs (especially for Docker builds in a CI), it would be great to define a cache dir location so that the dependencies can be cached between build jobs. 

Vaguely inspired by: https://medium.com/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0

**Comment by ruben-arts** [comment]
Hey @trahloff,

For the caching you can hard code it for now as we use a standard location for the cache ( `$HOME/.cache/rattler/cache` ). 
Here is an example docker file (for the pixi project itself):
```dockerfile
FROM ubuntu:latest
RUN apt update && apt install curl bash --yes

RUN curl -fsSL https://pixi.sh/install.sh | bash
ENV PATH="${PATH}:/root/.pixi/bin/"

RUN mkdir -p /root/pixi
WORKDIR /root/pixi

# Copy the project and lockfile to only reinstall if those are changed.
COPY pixi.lock pixi.toml ./

# Install the environment
RUN --mount=type=cache,target=/root/.cache/rattler pixi install

# Copy the rest of the project
COPY . ./
```
Specifically look at the trick with the `--mount` of a cache. This will only be touched when the `pixi.lock` or `pixi.toml` change, making this a fast docker image build if you only change your projects code.

If you're using a pixi install in a running docker image instead of a `docker build` you can mount this same folder to the local folder on your system. This way your systems cache will be shared with the cache in the docker image.
```
docker run -v ~/.cache/rattler/cache:/root/.cache/rattler/cache -it DOCKER_IMAGE_TAG
```
I hope this helps you for now?

**Comment by ruben-arts** [comment]
Close issue for now as we think there is no direct need for it right now. Reopen of there is a different reason for this feature!
