### ISSUE TITLE
Pixi does not seem to respect the current directory

### ISSUE THREAD

**Issue by datapythonista** [prefix-dev/pixi#376]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ cd subdir
$ pixi run pwd
/pixi-env-dir/
```

### Issue description

Seems like `pixi run` changes the working directory to the base project directory. Not sure if I'm missing something, but this seems the source of many problems, starting by a simple `pixi run ls` possibly showing the content of a different directory than the one where it's being executed, `pixi run jupyter lab` not using the subdirectory where it is executed, or in my case when using pixi to run pandas benchmarks, asv is failing since it's looking for the configuration file in the current directory, which pixi changed.

Am I missing something obvious, or is this a bug? Thanks!

### Expected behavior

```shell
$ cd subdir
$ pixi run pwd
/pixi-env-dir/subdir
```

**Comment by ruben-arts** [comment]
Yes this is true, to be more specific it will always use the directory of the root of the pixi project. This is by design but not set in stone. 

Its done so all pixi tasks will run from that location. 

There are multiple ways of changing this: 
- Defaulting to `cwd` of the shell.
- Defaulting to `project.root()` for predefined tasks but to `cwd` for unknown commands.
- Supporting a `--cwd` variable to specify the location of where you want to run this command. 
And probably more.

What would you think would be a nice way of doing this?

**Comment by baszalmstra** [comment]
Note that this behavior stems from deno_task_shell: https://docs.deno.com/runtime/manual/tools/task_runner#specifying-the-current-working-directory

**Comment by baszalmstra** [comment]
I would prefer:

> Defaulting to project.root() for predefined tasks but to cwd for unknown commands.

And allow users to use INIT_CWD to get the current working directory.

**Comment by pavelzw** [comment]
I agree with bas. I think this would be the most sensible way to handle this.

**Comment by datapythonista** [comment]
> Defaulting to project.root() for predefined tasks but to cwd for unknown commands.

This seems like a great idea to me

**Comment by ruben-arts** [comment]
Then lets do that!
