### ISSUE TITLE
Unusable slow solve for large dependency set

### ISSUE THREAD

**Issue by bounlu** [prefix-dev/pixi#391]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi add tiddit ascat cnvkit control-freec bedtools biscuit delly gridss manta lumpy-sv smoove sansa survivor svanalyzer svdb truvari rtg-tools numpy scipy cython cytoolz cyvcf2 pysam pyvcf pyfaidx toolshed
```

### Issue description

After initializing project, adding the above packages freezes pixi forever.

### Expected behavior

I thought pixi resolved dependency issues related to conda/mamba as a speedy alternative to install packages.

**Comment by wolfv** [comment]
@bounlu what channels are you using?

**Comment by wolfv** [comment]
And what platform? Linux-64?

**Comment by ruben-arts** [comment]
He @bounlu, we're trying to recreate the issue and it indeed runs forever but that also happens on `micromamba`. Did it ever finish for you? 

To get more info on these issues it is always good to check `pixi add -vvvv [PACKAGENAMES]` maybe it helps you understand the long solve. 

Otherwise it is always good to set some of the version (ranges) you want to solver to use. It feels like this solve has almost unlimited options but there might be some version you could give to solver to eliminate the time it needs to check all the options.

**Comment by bounlu** [comment]
@wolfv `conda-forge` and `bioconda` with Linux-64

**Comment by bounlu** [comment]
I am new to `pixi` so I was testing it up. I can install all those tools without version restriction but under different environments (most even require python2). I thought `pixi` does some magic on the dependency resolving that conda / mamba / microbamba could not achieve. So does `pixi` also rely on `micromamba`?

**Comment by ruben-arts** [comment]
It could be that the solver is trying to mix and match `python3` and `python2` dependencies.

`pixi` integrates a faster solver, [resolvo](https://github.com/mamba-org/resolvo), this is a faster solver then the one used in `micromamba`. So it should be faster then `conda`, `mamba` and `micromamba`. But we're very curious to find some more edge cases. 
That's why I hoped this set would be solvable but after 15 minutes my solve was still running, so in this case you might need to help the solver a little bit. 

I hope this message helps you understand it better. Also feel free to join our [discord](https://discord.gg/kKV8ZxyzY4) if you want to have a more direct form of communication.

**Comment by ruben-arts** [comment]
Closing as stale
