### ISSUE TITLE
pixi add python error

### ISSUE THREAD

**Issue by Liripo** [prefix-dev/pixi#453]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

`pixi.toml` 
```shell
[project]
name = "pixi-hello-world"
version = "0.1.0"
description = ""
authors = ["Liripo <liripo@qq.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.12.0.*"
```

### Issue description

![image](https://github.com/prefix-dev/pixi/assets/54770415/ec7709a9-24af-485d-990d-b1c099434673)
I got an error when I started running `pixi add python`

### Expected behavior

I am running it in the image `rocker/tidyverse:latest`.
```sh
> uname -a
Linux bac0711f600c 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Comment by ruben-arts** [comment]
I wasn't able on both `WSL2` and `Fedora` . 
A few questions:
- Are you using a mounted volume, if so does the issue persist when not using that.
- Did you try it on a different docker, Ubuntu:latest perhaps.
- Do you have any issues using pixi directly on WSL or Windows itself?

**Comment by Liripo** [comment]
I still get this error when running in `wsl2`.

**Comment by ruben-arts** [comment]
As you cannot hardlink over different file systems and a docker volume is seen as such it will not be possible to use a docker volume for you pixi environment.

**Comment by Liripo** [comment]
OK, thanks for the help.

**Comment by JnsJensen** [comment]
I am having this exact issue using pixi with WSL2, is it at all planned to have this be possible at some point, or is there a fundamental issue with making it happen?

**Comment by ruben-arts** [comment]
> I am having this exact issue using pixi with WSL2, is it at all planned to have this be possible at some point, or is there a fundamental issue with making it happen?

There is currently no plan to support this as it is a fundamental function that doesn't allow for this. Is there a specific reason you would want support for cross filesystem support?

**Comment by JnsJensen** [comment]
The specific case is for unrestricted use with WSL in my case. I currently switch between working on a Linux laptop and my Windows desktop with WSL. I love using pixi on my laptop, and am disappointed every time I sit at my desktop. I have chosen to have repos on the Windows filesystem, as it makes it easier for Windows applications to interact with them if necessary, since the host system is Windows. But I suppose simply switching to have my pixi projects on the linux file system instead of the Windows one would be a workaround. I have tested it a little bit, and seems to not be a problem, which is also how I understand it should behave from what you write?
