### ISSUE TITLE
JSON Schema for pixi.toml

### ISSUE THREAD

**Issue by brad-jones** [prefix-dev/pixi#592]
### Problem description

Just saying it would be nice to have a JSON Schema for the `pixi.toml` file for use with tooling like https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml#completion-and-validation-with-json-schema

**Comment by ruben-arts** [comment]
100% agree! I think it's important for us to have this auto-generated. Seeing tools like https://github.com/GREsau/schemars this might not be to hard. 

Open to contributions!

**Comment by orhun** [comment]
I tried to do this with `schemars` however it requires all fields of the type to implement [`JsonSchema`](https://docs.rs/schemars/latest/schemars/trait.JsonSchema.html), which means it fails for the following external types for `ProjectManifest` type:

- `rattler_conda_types::Version`
- `rattler_conda_types::Channel`
- `pep440_rs::VersionSpecifiers`

That's why we get a bunch of errors:

```
error[E0277]: the trait bound `rattler_conda_types::Version: JsonSchema` is not satisfied
    --> src/project/manifest.rs:1057:44
     |
1057 | #[cfg_attr(feature = "json-schema", derive(schemars::JsonSchema))]
     |                                            ^^^^^^^^^^^^^^^^^^^^ the trait `JsonSchema` is not implemented for `rattler_conda_types::Version`
```

The solution is to implement `JsonSchema` for these types 💀 

I already enabled some feature flags to make it work with several other crates:

```toml
schemars = { version = "0.8.16", features = ["url", "indexmap2"], optional = true }
```

[Here](https://github.com/GREsau/schemars/tree/master/schemars#feature-flags) is all the crates that `ProjectManifest` supports.

Thoughts?

**Comment by baszalmstra** [comment]
In the project model refactor Im also significantly refactoring the deserialization, where I implement custom deserializers for a bunch of types, Im a little scared that this doesnt help the case for schemars. 😨

**Comment by ruben-arts** [comment]
@orhun Thanks for the research! I think it is smart to delay this until the refactor is in.

**Comment by pavelzw** [comment]
I created a PR here: https://github.com/SchemaStore/schemastore/pull/3647

**Comment by pavelzw** [comment]
The schema is now part of schemastore and thus vscode etc use it without manually specifying the schema URL (works for rattler-build `recipe.yaml`s now too and conda-forge's `conda-forge.yml`). This issue can be closed now.

**Comment by ruben-arts** [comment]
That's amazing @pavelzw!

**Comment by wolfv** [comment]
We should tweet about this :)
