### ISSUE TITLE
Add `pixi runx package@version`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#624]
### Problem description

It would be nice to have the ability to do something like `npx`, `pnpx` or https://github.com/pkgxdev/pkgx; i.e., run any conda package without installing it globally (and without installing it in your pixi project environment(s)).
Pixi should create a temporary environment and run the command in this environment.

How about the following syntax?

```bash
$ pixi runx conda-smithy
<downloads conda-smithy@latest and runs `conda-smithy`>
$ pixi runx rattler-build@0.5.0 -- build
<downloads rattler-build@0.5.0 and runs `rattler-build build`>
$ pixi runx rattler-build --command "rattler-build2 build"
<downloads rattler-build and runs `rattler-build2 build` (needed for packages where the executable differs from the package name)>
```

I don't think we should support multiple requirements, I cannot think of a specific use case where you would need to specify multiple requirements at once to run a one-off command.

**Comment by tdejager** [comment]
Pretty good idea!

**Comment by hadim** [comment]
`pixi runx conda-forge/conda-smithy` or `pixi runx https://github.com/conda-forge/conda-smithy` as well no?

**Comment by pavelzw** [comment]
The first one yes 👍🏻 
The second one no since pixi has no idea what `https://github.com/conda-forge/conda-smithy` is and the repo also doesn't tell pixi where the corresponding conda package lies / how to build itself.

**Comment by hadim** [comment]
It could work if a build logic is set in the pixi manifest (not available yet but on the roadmap I believe) no?

**Comment by pavelzw** [comment]
Ah yes but I think this is still a somewhat long way to go for now :)

**Comment by ruben-arts** [comment]
Yes, we first put our focus on making rattler-build`

**Comment by jaimergp** [comment]
> `$ pixi runx rattler-build --command "rattler-build2 build"`

Interestingly, `npx` choose to take the main argument as the executable name. If they don't match (or the package provides several binaries to choose from), then the user can specify `--package exe-provider` instead.

So it would look like (with `--spec` instead of npx's `--package`):

```bash
$ pixi runx --spec=rattler-build rattler-build2 build
```

, which imo feels more natural than retrofitting args and commands, if that makes sense. It would also allow to specify several packages, in case there are e.g. optional dependencies that improve performance:

```bash
$ pixi runx --specs=some-project --spec=gpu-plugin some-project --with-gpu
```

Or maybe with `--specs` instead:

```bash
$ pixi runx --specs="some-project gpu-plugin" some-project --with-gpu
```

Or with a mix, having `--spec` and `--extra-specs` (so `spec` is the only one providing binaries, while `extra-specs` just fill in dependencies but don't contribute their binaries to PATH):

```bash
$ pixi runx --spec=some-project --extra-specs=gpu-plugin some-project --with-gpu
```

**Comment by pavelzw** [comment]
I also like this approach.

I'm in favor of not having `extra-specs`, though, that sounds oddly specific and I cannot think of a real world example that makes sense and would need this 👀
