### ISSUE TITLE
`pixi add helium --pypi` also downloads conda repodata

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#666]
```shell
pixi add helium --pypi
```
downloads repodata

### Expected behavior

I think when we add `--pypi` dependency we shouldn't need to download repodata for conda packages (since they shouldn't be changed by this operation).

**Comment by tdejager** [comment]
If you want to let this work correctly we should be able to check which part of the lock file is out of date. E.g conda or pypi dependencies, otherwise this would not function correctly.

For example, if the user manually changes the python version, then runs a `pixi add --pypi` we *do* actually need to update the repodata as well.

**Comment by ruben-arts** [comment]
Doesn't do that anymore
