### ISSUE TITLE
`console` already respects environment variables

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#835]
We added support for some color-forcing env vars but console already respects some:

https://github.com/console-rs/console/blob/de2f15a31a8fef0b0e65ef4bdf92cd03c3061dac/src/utils.rs#L30-L40

So we could get rid of the logic.

Console respects: CLICOLOR and CLICOLOR_FORCE.

**Comment by baszalmstra** [comment]
I think it would be good to support this standard but also keep our current handling because that's another "standard" and has already been used in a couple of places. Unfortunately, I don't think we can directly use the implementation from `console` because it's difficult to mix the different behaviors. (`CLICOLOR_FORCE` could overwrite the enabling through another flag)
