### ISSUE TITLE
Pixi removing packages installed by `uv` not part of `pixi.toml`

### ISSUE THREAD

**Issue by tadejsv** [prefix-dev/pixi#998]
I am installing a package from github (`git+ssh://`) using `uv`, as [pixi does not support this yet](https://github.com/prefix-dev/pixi/issues/879). However, whenever I run any `pixi` command (even just `pixi shell`), this package gets uninstalled.

Is this really the desired behavior? Why not just issue a warning if non pixi-managed package is found? Or at least give an option to disable this behavior?

For now I am simply switching to installing with `pip`, which works, but is inferior to installing with `uv`

**Comment by ruben-arts** [comment]
He @tadejsv, this is an good find. 
This is most likely because we also use `uv` and "our" `uv` is getting the instruction to uninstall packages that are not needed anymore (based on requirements). As `uv` finds both `pixi`'s and your `uv` packages it acts on them as equal.

@tdejager I know we're going to support all this behavior but would it be possible to make sure we only uninstall pixi installed packages? By making the `INSTALLER` `uv-pixi` or something like that.

**Comment by wolfv** [comment]
I made a quick PR to `uv` here: https://github.com/astral-sh/uv/pull/2561

**Comment by tdejager** [comment]
I agree I think that would be the only option, it can potentially keep
brealking for newer versions of pixi as long as people have not cleared
their environments so we might need to add something to the release notes
for that.

Let’s hope uv accepts that PR soon :)

**Comment by tdejager** [comment]
Uv has merged this so we should update and add the installer in the relevant places :)
